### ISSUE TITLE
Adding "time" of the sent message by an user

### ISSUE THREAD

**Issue by sushovanb02** [osBins/chatApp#65] opened 2021-12-06 12:37 UTC
@PrimalPimmy @osBins  kindly assign me this for KWoC 2021

**Comment by osBins** [comment] 2021-12-06 13:11
Appreciate your interest in contributing to the chatApp @sushovanb02! However, this is a duplicate of issue #49, which already has someone assigned.
Feel free to go through the list of issues/create another one yourself to work on. Cheers!

**Closed** 2021-12-06 13:12 UTC
Labels: duplicate
